/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/lib')['VAppBarNavIcon']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VMain: typeof import('vuetify/lib')['VMain']
    VRow: typeof import('vuetify/lib')['VRow']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
  }
}
