import Vue from 'vue';
import Vuetify, {
  VApp,
  VList,
  VListItem,
  VListItemIcon,
  VListItemTitle,
  VListItemSubtitle,
  VListItemAction,
  VListItemActionText,
  VListItemContent,
  VListItemAvatar,
  VAvatar,
  VContainer,
  VTextField,
  VSelect,
  VCheckbox,
  VCombobox,
  VAutocomplete,
  VDialog,
  VMenu,
  VImg,
  VHover,
  VTooltip,
  VSheet,
  VCard,
  VCardTitle,
  VCardText,
  VCardActions,
  VIcon,
  VChip,
  VSpacer,
  VBtn,
  VRow,
  VCol,
  VProgressLinear,
  VDataTable,
  VSimpleTable,
  VVirtualScroll,
  VSkeletonLoader,
  VFadeTransition,
  VExpandTransition,
  VFileInput,
  VBanner,
  VAppBar,
  VToolbarTitle,
  VAlert,
  VBadge,
} from 'vuetify/lib';
import { Ripple, Scroll, Intersect } from 'vuetify/lib/directives';

Vue.use(Vuetify, {
  components: {
    VApp,
    VList,
    VListItem,
    VListItemIcon,
    VListItemTitle,
    VListItemSubtitle,
    VListItemAction,
    VListItemActionText,
    VListItemContent,
    VListItemAvatar,
    VAvatar,
    VContainer,
    VTextField,
    VSelect,
    VCheckbox,
    VCombobox,
    VAutocomplete,
    VDialog,
    VMenu,
    VImg,
    VHover,
    VTooltip,
    VSheet,
    VCard,
    VCardTitle,
    VCardText,
    VCardActions,
    VBadge,
    VIcon,
    VChip,
    VSpacer,
    VBtn,
    VRow,
    VCol,
    VProgressLinear,
    VDataTable,
    VSimpleTable,
    VVirtualScroll,
    VSkeletonLoader,
    VFadeTransition,
    VExpandTransition,
    VFileInput,
    VBanner,
    VAppBar,
    VToolbarTitle,
    VAlert,
  },
  directives: {
    Ripple,
    Scroll,
    Intersect,
  },
});

export default function VuetifyConfig() {
  const opts = {
    theme: {
      themes: {
        light: {
          primary: '#448AFF',
          success: '#00A354',
          secondary: '#00A354',
        },

        dark: {
          primary: '#448AFF',
          success: '#00A354',
          secondary: '#00A354',
        },
        iconfont: 'mdiSvg',
      },
      options: { customProperties: true },
    },
  };
  return new Vuetify(opts);
}
